name: fidely_key
description: "A secure, cross-platform 2FA authentication application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5

  # Data & Serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  uuid: ^4.4.0

  # Security & Storage
  flutter_secure_storage: ^9.2.2
  encrypt: ^5.0.3

  # Scanner
  mobile_scanner: ^5.2.3

  # UI & Design
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3
  simple_icons: ^14.6.1
  shimmer: ^3.0.0

  # TOTP Logic
  otp: ^3.1.0
  base32: ^2.1.1 # Useful for decoding secrets
  local_auth: ^3.0.0
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  crypto: ^3.0.7
  pdf: ^3.11.3
  printing: ^5.14.2
  ntp: ^2.0.0
  hotkey_manager: ^0.2.3
  window_manager: ^0.5.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  home_widget: ^0.7.0
  cached_network_image: ^3.3.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "lib/assets/icon/logo.png"
    background_color: "#121212"
    theme_color: "#2563EB"
  windows:
    generate: true
    image_path: "lib/assets/icon/logo.png"
    icon_size: 48

flutter_native_splash:
  color: "#121212"
  image: lib/assets/icon/logo.png
  android_12:
    image: lib/assets/icon/logo.png
    color: "#121212"
